[chameleon]
endpoint = "http://localhost:8080"

[ubiAd]
endpoint = "http://localhost:8100"

[mongo]
endpoint = "localhost:27017"
DBName = "ubiquitous-signage"

[wordCloud]
thinOutThreshold = 70
reductionRatio = 0.4

[schedule]
startDelaySecond = 3
sleepSecond = 60

[portal]
startDelaySecond = 6
sleepSecond = 60

[newsletter]
startDelaySecond = 9
sleepSecond = 60

[lecture]
startDelaySecond = 12
sleepSecond = 60
